// Configfuration for our tokens

const NUM_JUNGLE_ROADS_OPTIONS = 25;
const MINT_INITIAL_SUPPLY = 0;
const MINT_LOOTBOX_INITIAL_SUPPLY = 0;

const CLASS_COMMON = 0;
const CLASS_UNCOMMON = 1;
const CLASS_RARE = 2;
const CLASS_LEGENDARY = 3;
const CLASS_IMMORTAL = 4;
const NUM_CLASSES = 5;

const LOOTBOX_OPTION_ID = 0;
const LOOTBOX_OPTION_AMOUNT_PER_BOX = 1;
const LOOTBOX_OPTION_PROPABILITIES = [7300, 2100, 400, 100, 100];

const NO_SUCH_ITEM_OPTION = 9999;

const TOKEN_IDS_FOR_CLASSES = [
  [0, 5, 10, 15, 20],
  [1, 6, 11, 16, 21],
  [2, 7, 12, 17, 22],
  [3, 8, 13, 18, 23],
  [4, 9, 14, 19, 24],
];

module.exports = {
  NUM_JUNGLE_ROADS_OPTIONS,
  MINT_INITIAL_SUPPLY,
  MINT_LOOTBOX_INITIAL_SUPPLY,
  CLASS_COMMON,
  CLASS_UNCOMMON,
  CLASS_RARE,
  CLASS_LEGENDARY,
  CLASS_IMMORTAL,
  NUM_CLASSES,
  LOOTBOX_OPTION_ID,
  NO_SUCH_ITEM_OPTION,
  LOOTBOX_OPTION_AMOUNT_PER_BOX,
  LOOTBOX_OPTION_PROPABILITIES,
  TOKEN_IDS_FOR_CLASSES,
};
